### PR TITLE
Fix/improved errors

### LINKED ISSUE #333: Protocol load error displays could be improved
When a protocol fails to load (or process to completion), the error message presented in the GUI may be unhelpful (e.g., `[Object object]`). The basic test case is to enter a custom URL and tap load protocol.

Note, I see a reasonable error message on electron for 404s, although the displayed URL ("stuk.github.io/jszip/documentation/howto/read_zip.html") looks like developer documentation...

I wonder if having our own generic error message for all of these cases is preferable (or perhaps one for network/server and one for processing).

## [Electron] When URL is a directory

electron-folder

## [iOS] URL that 404s

ios-404

(Any 404 should do, but URL tested was the default, minus the final "s".)

## [Electron] SSL trust error

This may not be an issue in practice, but can be reproduced by importing from a server using a self-signed cert (e.g., the dev server in https mode). In this case, no error is presented. There's an uncaught error in the console and the app spinner displays indefinitely until the app is reloaded.

### PR DESCRIPTION
**Pull request by wwqrd**
Resolves #333

Adds human readable errors for download/import/load protocol, and pattern for handling errors in future.

 # Known issues
- [x] Functions that aren't defined for a particular environment throw errors. Do they need to return promises for correct handling? If so update to Promise.reject()
- [x] Re-test on devices

### CODE REVIEW

File: src/utils/protocol/importProtocol.js [hunk 1]
```diff
@@ -86,6 +77,28 @@ const extractZip = inEnvironment((environment) => {
...
 
+const loadZip = inEnvironment((environment) => {
+  if (environment === environments.CORDOVA || environment === environments.ELECTRON) {
+    return source =>
+      readFile(source)
+        .then(data => Zip.loadAsync(data))
+        .catch(friendlyErrorMessage("We couldn't find a Network Canvas protocol at the location you gave us. Check the location, and try again."));
+  }
+
+  throw new Error(`loadZip() not available on platform ${environment}`);
```
Comment (jthrilly) [inline src/utils/protocol/importProtocol.js]: Do `loadZip()` errors not trigger a friendly error? What happens to them? What should the user do?

File: src/utils/protocol/downloadProtocol.js [hunk 2]
```diff
@@ -23,27 +27,37 @@ const downloadProtocol = inEnvironment((environment) => {
...
-              encodeURI(uri),
+              url,
               destination,
               () => resolve(destination),
               error => reject(`Error code: ${error.code}. (${error.source})`),
             );
           }),
-        );
+        )
+        .catch(friendlyErrorMessage("Your device doesn't have an active internet connection, so we weren't able to fetch your protocol at this time. Connect to a network, and try again."));
```
Comment (jthrilly) [inline src/utils/protocol/downloadProtocol.js]: Should this be "active network connection", since some protocol URLs could be local?

File: src/utils/protocol/importProtocol.js (hunk 1 above)
Comment (wwqrd) [reply src/utils/protocol/importProtocol.js]: There are two workflows going on here:

1. You called a method that isn't supported on the platform
1. One of the steps threw an error.

This is the first one, which will probably go straight to the console at the moment, since it's the wrong type for our promise chains (separate issue: it's generally good practice to always return the same type, so maybe we should return a promise rejection here?).

Should we capture this kind of error for the user? I'm not sure. What do you thing?

File: src/utils/protocol/downloadProtocol.js [hunk 3]
```diff
@@ -23,27 +27,45 @@ const downloadProtocol = inEnvironment((environment) => {
     return (uri) => {
       const tempPath = (electron.app || electron.remote.app).getPath('temp');
 
-      return getProtocolNameFromUri(uri)
-        .then(protocolName => path.join(tempPath, protocolName))
-        .then(destination => writeStream(destination, request(uri)));
+      return getURL(uri)
```
Comment (bryfox) [inline src/utils/protocol/downloadProtocol.js]: There's another case here that isn't caught; I'm not sure why. It's described by the SSL trust case in #331 but happens more generally any time a remote server can't be reached.

Test by hitting a well-formed URL at `localhost:7788` (any non-running local port) or some hostname known to not exist.

In these cases, an uncaught error shows in the console and UI spins indefinitely until reload. If we expect users to be able to import from arbitrary servers, it would be good to catch this case.

(I'm on electron/macOS.)

File: src/utils/protocol/importProtocol.js (hunk 1 above)
Comment (jthrilly) [reply src/utils/protocol/importProtocol.js]: I'm just thinking in terms of testing. Users won't have the console open, so will have no means of knowing what happened. I realise this is basically a noop, but we want to show an error when things that shouldn't happen do. I think returning a promise rejection is the right thing to do.

**Comment by rebeccamadsen** [comment]
On Chrome, when the app loads, the console shows the following warning:
```
Warning: Failed prop type: Invalid prop `additionalInformation` supplied to `Dialog`.
    in Dialog (at ErrorMessage.js:35)
    in ErrorMessage (created by Connect(ErrorMessage))
    in Connect(ErrorMessage) (at App.js:40)
    in div (at App.js:18)
    in App (created by Connect(App))
    in Connect(App) (at index.js:17)
    in Provider (at index.js:16)
__stack_frame_overlay_proxy_console__ @ bundle.js:227145
```

File: src/utils/protocol/downloadProtocol.js (hunk 3 above)
Comment (wwqrd) [reply src/utils/protocol/downloadProtocol.js]: Great catch!

**Comment by wwqrd** [comment]
@rebeccamadsen Chrome issue should be resolved
@jthrilly The environment errors now respect type, so will get captured in the promise methods
@bryfox I've updated this to use promises rather than streaming, which proved very difficult to capture. The electron errors are now much more fine grained, the Cordova ones are still a bit indiscriminate.

**Comment by jthrilly** [comment]
Looks great to me.

**Comment by bryfox** [comment]
Confirmed chrome issue is fixed as well.
